# Generated by Django 4.2 on 2023-06-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askmeWEB', '0002_answer_question_question_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='to_question',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
