# Generated by Django 4.2 on 2023-06-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeWEB', '0005_alter_profile_avatar_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('-', 'dislike'), ('+', 'like')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('from_user', 'to_question')},
        ),
    ]
